name: "📚 Documentation Request"
description: Request an update or creation of documentation.
title: "📚 [DOC] - <title>"
labels: [
 "documentation"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please describe the documentation update or creation needed.
      placeholder: Short and explicit description of the documentation request...
    validations:
      required: true
  - type: input
    id: affected_sections
    attributes:
      label: "Affected Sections"
      description: Specify the sections or files in the documentation that need updates.
      placeholder: ex. `README.md`, `CONTRIBUTING.md`
    validations:
      required: true
  - type: textarea
    id: proposed_changes
    attributes:
      label: "Proposed Changes"
      description: Describe the proposed changes to the documentation.
      placeholder: Detailed explanation of the changes...
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: Add any additional context or information here.
      placeholder: Any other details or notes...
    validations:
      required: false
